name = "XUnit"
uuid = "3e3c03f2-1a94-11e9-2981-050a4ca824ab"
authors = ["Mohammad Dashti <mdashti@gmail.com>"]
version = "1.1.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ExceptionUnwrapping = "460bff9d-24e4-43bc-9d9f-a8973cb893f4"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestReports = "dcd651b4-b50a-5b6b-8f22-87e9f253a252"

[compat]
ExceptionUnwrapping = "0.1"
EzXML = "1"
TestReports = "0.4"
julia = "1.3, 1.5"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[targets]
test = ["Pkg", "Logging"]
